title: Bienvenue le site de Mr Antoine
description: Exercices et devoirs de maths
remote_theme: just-the-docs/just-the-docs

# Active la recherche et le menu
nav_enabled: true
search_enabled: true

# CONFIGURATION MATHÃ‰MATIQUE
# On injecte le script MathJax directement dans le site
head_scripts:
  - "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
