title: Mr Antoine
description: Le générateurs d'exercices et devoirs de maths
remote_theme: just-the-docs/just-the-docs

# Active la recherche et le menu
nav_enabled: true
search_enabled: false

# CONFIGURATION MATHÉMATIQUE
# Charger MathJax pour transformer le code en jolies formules
head_scripts:
  - "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
