title: Mr Antoine
description: Le générateurs d'exercices et devoirs de maths
remote_theme: just-the-docs/just-the-docs

# Active la recherche et le menu
nav_enabled: false
search_enabled: false

# CONFIGURATION MATHÉMATIQUE
# On injecte le script MathJax directement dans le site
head_scripts:
  - "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
