title: Site de Mr Antoine
description: Mon générateur d'exercices et de devoirs
theme: jekyll-theme-minimal
remote_theme: just-the-docs/just-the-docs

# Configuration du thème
nav_enabled: true
search_enabled: true

# Pour que les maths s'affichent (MathJax)
aux_links:
  "Mon GitHub": "https://github.com/medi00974"

# On ajoute cette partie pour charger MathJax sur toutes les pages
common_ext:
  - mathjax
